---
- name: Migration AAP24RPM to AAP24OCP
  hosts: all
  #connection: local
  gather_facts: true

  vars:
    pg_password: Admin123!
    pg_user: awx
  
  tasks:
  # Gather facts of all instances Controller/Automation Hub/PostgreSQL/Execution Nodes
  - name: Gather facts of all instances
    debug:
      var: ansible_facts

  - name: Verify PostgreSQL version
    ansible.builtin.command: "psql -U {{ pg_user }} -c 'SELECT version();'"
    environment:
      PGPASSWORD: "{{ pg_password }}"
    register: postgresql_version
    when: "'database' in group_names"

  - name: Display PostgreSQL version
    debug:
      msg: "{{ postgresql_version.stdout }}"
    when: "'database' in group_names"