---
- name: Migration AAP24RPM to AAP24OCP
  hosts: all
  #connection: local
  gather_facts: true

  vars:
    pg_password: Admin123!
  
  tasks:
  # Gather facts of all instances Controller/Automation Hub/PostgreSQL/Execution Nodes
  - name: Gather facts of all instances
    debug:
      var: ansible_facts

  - name: Verify PostgreSQL version
    ansible.builtin.command: "PGPASSWORD='{{ pg_password }}' psql -h db.example.com -U myuser -d mydatabase -c 'SELECT version();'"
    register: postgresql_version
    when: "'postgresql' in group_names"

  - name: Display PostgreSQL version
    debug:
      msg: "{{ postgresql_version.stdout }}"
    when: "'postgresql' in group_names"