---
- name: Setup NFS Server on RHEL 9
  hosts: localhost
  become: true
  vars:
    nfs_share_path: "/nfs/exports/myshare"
    nfs_share_pulp_static: "{{ nfs_share_path }}/pulpcore_static"
    nfs_exports:
      - "192.168.8.112/24(rw,sync,no_root_squash,no_all_squash,anonuid=65534,anongid=65534)"
      - "192.168.8.167/24(rw,sync,no_root_squash,no_all_squash,anonuid=65534,anongid=65534)"

  tasks:
    - name: Install NFS utilities
      dnf:
        name: nfs-utils
        state: present

    - name: Create NFS share directory
      file:
        path: "{{ nfs_share_path }}"
        state: directory
        mode: '0777'
        owner: nobody
        group: nobody
        recurse: true

    - name: Create NFS share directory for pulpcore_static
      file:
        path: "{{ nfs_share_pulp_static }}"
        state: directory
        mode: '0777'
        owner: nobody
        group: nobody
        recurse: true

    - name: Configure NFS exports
      lineinfile:
        path: /etc/exports
        line: "{{ nfs_share_path }} {{ item }}"
        backup: true
        create: true
      loop: "{{ nfs_exports }}"
      notify:
        - reload nfs exports

    - name: Configure firewall for NFS services
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - nfs
        - rpc-bind
        - mountd
      notify:
        - reload firewall

    - name: Enable and start rpcbind service
      systemd:
        name: rpcbind
        enabled: true
        state: started

    - name: Enable and start NFS server service
      systemd:
        name: nfs-server
        enabled: true
        state: started

    - name: Verify NFS server is running
      command: systemctl is-active nfs-server
      register: nfs_status
      changed_when: false

    - name: Verify rpcbind is running
      command: systemctl is-active rpcbind
      register: rpcbind_status
      changed_when: false

    - name: Display NFS service status
      debug:
        msg:
          - "NFS Server Status: {{ nfs_status.stdout }}"
          - "RPC Bind Status: {{ rpcbind_status.stdout }}"

    - name: Show current NFS exports
      command: exportfs -s
      register: current_exports
      changed_when: false

    - name: Display current NFS exports
      debug:
        msg: "Current NFS Exports: {{ current_exports.stdout_lines }}"

    - name: Test showmount on localhost
      command: showmount -e localhost
      register: showmount_output
      changed_when: false

    - name: Display showmount results
      debug:
        msg: "Showmount output: {{ showmount_output.stdout_lines }}"

  handlers:
    - name: reload nfs exports
      command: exportfs -arv

    - name: reload firewall
      command: firewall-cmd --reload