---
- name: Netbox VM Instance onboarding
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    netbox_url: "http://{{ netbox_endpoint }}:8000"  # Replace with your NetBox URL
    netbox_token: "{{ netbox_vault_token }}"  # Replace with your NetBox API token
    netbox_cluster: "aws-cluster"  # Replace with your NetBox cluster name

  tasks:
    - name: "Ping the NetBox API"
      ansible.builtin.uri:
        url: "{{ netbox_url }}/api/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        validate_certs: false  # Set to 'true' if you have a valid SSL certificate
        status_code: 200       # We expect a successful HTTP 200 OK
      register: result

    - name: "Display Connection Status"
      ansible.builtin.debug:
        msg: "Successfully connected to NetBox! API version: {{ result }}"

    - name: gather ec2 instance variables
      amazon.aws.ec2_instance_info:
        region: ap-southeast-2
        filters:
          "instance-type": "t2.micro"
      register: ec2_info

    - name: print ec2_info
      debug:
        var: ec2_info

    - name: Create NetBox VM Instance
      ansible.builtin.uri:
        url: "{{ netbox_url }}/api/virtualization/virtual-machines/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        validate_certs: false
        body: >
          {
            "name": "{{ ec2_info.instances[0].tags.Name }}",
            "cluster": "{{ netbox_cluster }}",
            "status": "active",
            "platform": "linux",
            "custom_fields": {
              "instance_id": "{{ ec2_info.instances[0].instance_id }}",
              "private_ip": "{{ ec2_info.instances[0].private_ip_address }}",
              "public_ip": "{{ ec2_info.instances[0].public_ip_address }}",
              "instance_type": "{{ ec2_info.instances[0].instance_type }}",
              "security_group_id": "{{ ec2_info.instances[0].security_groups[0].group_id }}"
            }
          }
        status_code: 201
      register: create_result

    - name: Display Creation Status
      ansible.builtin.debug:
        msg: "Successfully created NetBox VM Instance! ID: {{ create_result.id }}"
