---
- name: Netbox VM Instance onboarding
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    netbox_url: "http://{{ netbox_endpoint }}:8000"  # Replace with your NetBox URL
    netbox_token: "{{ netbox_vault_token }}"  # Replace with your NetBox API token

  tasks:
    - name: "Ping the NetBox API"
      ansible.builtin.uri:
        url: "{{ netbox_url }}/api/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        validate_certs: false  # Set to 'true' if you have a valid SSL certificate
        status_code: 200       # We expect a successful HTTP 200 OK
      register: result

    - name: "Display Connection Status"
      ansible.builtin.debug:
        msg: "Successfully connected to NetBox! API version: {{ result }}"

    - name: gather Netbox virtual machine clusters
      ansible.builtin.uri:
        url: "{{ netbox_url }}/api/virtualization/clusters/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        validate_certs: false  # Set to 'true' if you have a valid SSL certificate
        status_code: 200       # We expect a successful HTTP 200 OK
      register: netbox_clusters

    - name: "Display NetBox Clusters"
      ansible.builtin.debug:
        var: netbox_clusters

    - name: gather ec2 instance variables
      amazon.aws.ec2_instance_info:
        region: ap-southeast-2
        filters:
          "instance-type": "t2.micro"
      register: ec2_info

    - name: print ec2_info
      debug:
        var: ec2_info
    
    - name: print loop ec2_info.instances
      debug:
        msg: "{{ item.tags.Name | default(item.instance_id) }}"
      loop: "{{ ec2_info.instances }}"
      loop_control:
        label: "{{ item.tags.Name | default(item.instance_id) }}"

    - name: Create NetBox VM Instance
      ansible.builtin.uri:
        url: "{{ netbox_url }}/api/virtualization/virtual-machines/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        validate_certs: false
        body_format: json
        body: >
          {
            "name": "{{ item.tags.Name | default(item.instance_id) }}",
            "cluster": "{{ netbox_clusters.json.results[0].id }}",
            "status": "active",
            "custom_fields": {
              "instance_id": "{{ item.instance_id }}",
              "private_ip": "{{ item.private_ip_address }}",
              "public_ip": "{{ item.public_ip_address }}",
              "instance_type": "{{ item.instance_type }}",
              "security_group_id": "{{ item.security_groups[0].group_id }}"
            }
          }
        status_code: 201
      loop: "{{ ec2_info.instances }}"
      loop_control:
        label: "{{ item.tags.Name | default(item.instance_id) }}"
      register: create_result

    - name: Display Creation Status
      ansible.builtin.debug:
        msg: "Successfully created NetBox VM Instance! ID: {{ create_result.json.id }}, Name: {{ create_result.json.name }}"
