---
- name: Cisco ACI vlan delete
  hosts: aci
  connection: local
  gather_facts: no
  vars:
    username: admin
    password: redhat123
    hostname: 10.69.151.244

  tasks:
    - name: delete switch leaf profile
      cisco.aci.aci_switch_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        state: absent
        validate_certs: false
      
    - name: Query a leaf profile
      cisco.aci.aci_switch_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        state: query
        validate_certs: false
      register: query_result_leaf_profile

    - name: print switch leaf profile output
      ansible.builtin.debug:
        var: query_result_leaf_profile

    - name: delete leaf selector of switch profile
      cisco.aci.aci_switch_leaf_selector:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        leaf: leaf_selector_101
        leaf_node_blk: 101
        from: 101
        to: 101
        state: absent
        validate_certs: false

    - name: Query leaf selector of switch profile
      cisco.aci.aci_switch_leaf_selector:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        leaf: leaf_1
        leaf_node_blk: 101
        state: query
        validate_certs: false
      register: query_result_leaf_selector

    - name: print output of query result for leaf selector
      ansible.builtin.debug:
        var: query_result_leaf_selector

    - name: delete leaf interface profile
      cisco.aci.aci_interface_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: SW_Leaf_101_102
        state: absent
        validate_certs: false

    - name: Query leaf interface profile
      cisco.aci.aci_interface_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: SW_Leaf_101_102
        state: query
        validate_certs: false
      register: query_result_leaf_interface_profile
    
    - name: print output of query result for leaf interface profile
      ansible.builtin.debug:
        var: query_result_leaf_interface_profile

    - name: delete access port selector for leaf interface profile
      cisco.aci.aci_access_port_to_interface_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: SW_Leaf_101_102
        access_port_selector: SW_Leaf_101_102_access_port
        state: absent
        validate_certs: false
    
    - name: Query access port selector for leaf interface profile
      cisco.aci.aci_access_port_to_interface_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: SW_Leaf_101_102
        state: query
        validate_certs: false
      register: query_result_access_port_blk
    
    - name: print query result access port selector for leaf interface profile
      ansible.builtin.debug:
        var: query_result_access_port_blk 
    
    