---
- name: Cisco ACI vlan create
  hosts: aci
  connection: local
  gather_facts: no
  vars:
    username: admin
    password: redhat123
    hostname: 10.69.151.244

  tasks:
    - name: create switch leaf profile
      cisco.aci.aci_switch_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        description: created by Ansible
        validate_certs: false
        state: present

    - name: Query a leaf profile
      cisco.aci.aci_switch_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        state: query
        validate_certs: false
      register: query_result_leaf_profile
    
    - name: print switch leaf profile output
      ansible.builtin.debug:
        var: query_result_leaf_profile

    - name: adding leaf selector to switch profile
      cisco.aci.aci_switch_leaf_selector:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        leaf: leaf_1
        leaf_node_blk: 101
        from: 101
        to: 101
        state: present
        validate_certs: false

    - name: Query leaf selector of switch profile
      cisco.aci.aci_switch_leaf_selector:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        leaf: leaf_1
        leaf_node_blk: 101
        state: query
        validate_certs: false
      register: query_result_leaf_selector

    - name: print output of query result for leaf selector
      ansible.builtin.debug:
        var: query_result_leaf_selector

    - name: Add a new leaf interface profile
      cisco.aci.aci_interface_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: SW_Leaf_101_102
        description: created by Ansible
        validate_certs: false
        state: present

    - name: Query leaf interface profile
      cisco.aci.aci_interface_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: SW_Leaf_101_102
        state: query
        validate_certs: false
      register: query_result_leaf_interface_profile
    
    - name: print output of query result for leaf interface profile
      ansible.builtin.debug:
        var: query_result_leaf_interface_profile
    
    - name: Create access port selector for leaf interface profile
      cisco.aci.aci_access_port_to_interface_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: SW_Leaf_101_102
        access_port_selector: SW_leaf_interface_profile_access_port
        port_blk: SW_leaf_interface_profile_access_port_blk
        from_port: 5
        to_port: 7
        state: present
        validate_certs: false
    

    
    
    
    
    


    
    
    # - name: Query all cisco aci VLAN pool
    #   cisco.aci.aci_vlan_pool:
    #     host: "{{ hostname }}"
    #     username: "{{ username }}"
    #     password: "{{ password }}"
    #     validate_certs: false
    #     state: query
    #   register: vlan_pool
    
    # - name: print out VLAN
    #   ansible.builtin.debug:
    #     var: vlan_pool
    