---
- name: Cisco ACI vlan delete
  hosts: aci
  connection: local
  gather_facts: no
  vars:
    username: admin
    password: redhat123
    hostname: 10.69.151.244

  tasks:
    - name: delete switch leaf profile
      cisco.aci.aci_switch_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        state: absent
        validate_certs: false
      
    - name: Query a leaf profile
      cisco.aci.aci_switch_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        state: query
        validate_certs: false
      register: query_result_leaf_profile

    - name: print switch leaf profile output
      ansible.builtin.debug:
        var: query_result_leaf_profile

    - name: delete leaf selector of switch profile
      cisco.aci.aci_switch_leaf_selector:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        leaf: leaf_selector_101
        leaf_node_blk: 101
        from: 101
        to: 101
        state: absent
        validate_certs: false

    - name: Query leaf selector of switch profile
      cisco.aci.aci_switch_leaf_selector:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        leaf: leaf_1
        leaf_node_blk: 101
        state: query
        validate_certs: false
      register: query_result_leaf_selector

    - name: print output of query result for leaf selector
      ansible.builtin.debug:
        var: query_result_leaf_selector

    - name: delete leaf interface profile
      cisco.aci.aci_interface_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: SW_Leaf_101_102
        state: absent
        validate_certs: false

    - name: Query leaf interface profile
      cisco.aci.aci_interface_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: SW_Leaf_101_102
        state: query
        validate_certs: false
      register: query_result_leaf_interface_profile
    
    - name: print output of query result for leaf interface profile
      ansible.builtin.debug:
        var: query_result_leaf_interface_profile

    - name: delete access port selector for leaf interface profile
      cisco.aci.aci_access_port_to_interface_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: SW_Leaf_101_102
        access_port_selector: SW_Leaf_101_102_access_port
        state: absent
        validate_certs: false
    
    - name: Query access port selector for leaf interface profile
      cisco.aci.aci_access_port_to_interface_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: SW_Leaf_101_102
        state: query
        validate_certs: false
      register: query_result_access_port_blk
    
    - name: print query result access port selector for leaf interface profile
      ansible.builtin.debug:
        var: query_result_access_port_blk

    - name: Remove CDP Interface policy
      cisco.aci.aci_interface_policy_cdp:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        name: Ansible_CDP_OFF
        state: absent
        validate_certs: false

    - name: Query CDP Interface policy
      cisco.aci.aci_interface_policy_cdp:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        name: Ansible_CDP_OFF
        state: query
        validate_certs: false
      register: query_result_CDP_Interface_policy

    - name: print query result CDP Interface policy
      ansible.builtin.debug:
        var: query_result_CDP_Interface_policy

    - name: Remove LLDP Interface Policy
      cisco.aci.aci_interface_policy_lldp:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        lldp_policy: Ansible_LLDP_ON
        state: absent
        validate_certs: false

    - name: Query LLDP Interface policy
      cisco.aci.aci_interface_policy_lldp:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        lldp_policy: Ansible_LLDP_ON
        state: query
        validate_certs: false
      register: query_result_LLDP_Interface_policy

    - name: print query result LLDP Interface policy
      ansible.builtin.debug:
        var: query_result_LLDP_Interface_policy

    - name: Remove Port Channel Policy
      cisco.aci.aci_interface_policy_port_channel:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        port_channel: Ansible_LACP_ACTIVE
        mode: active
        state: absent
        validate_certs: false
    
    - name: Query Port Channel Policy
      cisco.aci.aci_interface_policy_port_channel:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        port_channel: Ansible_LACP_ACTIVE
        state: query
        validate_certs: false
      register: query_result_Port_Channel_policy
    
    - name: print query result Port Channel Policy
      ansible.builtin.debug:
        var: query_result_Port_Channel_policy

    - name: Remove Leaf Access Port Policy Group
      cisco.aci.aci_interface_policy_leaf_policy_group:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        policy_group: Ansible_Leaf_Access_Port_PG_Policy
        lag_type: leaf
        state: absent
        validate_certs: false
    
    - name: Query Leaf Access Port Policy Group
      cisco.aci.aci_interface_policy_leaf_policy_group:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        policy_group: Ansible_Leaf_Access_Port_PG_Policy
        lag_type: leaf
        cdp_policy: Ansible_CDP_ON
        lldp_policy: Ansible_LLDP_OFF
        state: query
        validate_certs: false
      register: query_result_leaf_access_port_pg

    - name: print query result Leaf Access Port Policy Group
      ansible.builtin.debug:
        var: query_result_leaf_access_port_pg

    - name: Remove VPC Interface Policy Group
      cisco.aci.aci_interface_policy_leaf_policy_group:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        policy_group: Ansible_VPC_Interface_PG_Policy
        lag_type: node
        cdp_policy: Ansible_CDP_ON
        lldp_policy: Ansible_LLDP_OFF
        state: absent
        validate_certs: false

    - name: Query VPC Interface Policy Group
      cisco.aci.aci_interface_policy_leaf_policy_group:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        policy_group: Ansible_VPC_Interface_PG_Policy
        lag_type: node
        state: query
        validate_certs: false
      register: query_result_vpc_interface_pg

    - name: print query VPC Interface Policy Group
      ansible.builtin.debug:
        var: query_result_vpc_interface_pg

    - name: Remove Interface Selector Profile associated with a switch ppolicy leaf profile
      cisco.aci.aci_interface_selector_to_switch_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        interface_selector: SW_Leaf_101_102
        state: absent
        validate_certs: false

    - name: Query Interface selector profile to switch leaf profile
      cisco.aci.aci_interface_selector_to_switch_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        state: query
        validate_certs: false
      register: query_result_Interface_Profile_leaf_profile

    - name: Print query result of Interface Profile of Leaf Profile
      ansible.builtin.debug:
        var: query_result_Interface_Profile_leaf_profile

    - name: Remove associated Interface Policy group to Leaf Interface Profile with a policy group
      cisco.aci.aci_access_port_to_interface_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        interface_profile: SW_Leaf_101_102
        access_port_selector: SW_leaf_interface_profile_access_port
        state: absent
        validate_certs: false

    - name: Query Interface Policy group associated to Leaf Interface Profile
      cisco.aci.aci_access_port_to_interface_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        interface_profile: SW_Leaf_101_102
        access_port_selector: SW_leaf_interface_profile_access_port
        state: query
        validate_certs: false
      register: query_result_Interface_Policy_Group_leaf_Interface_profile

    - name: Print Query result of Interface Policy Group associated to Leaf Interface Profile
      ansible.builtin.debug:
        var: query_result_Interface_Policy_Group_leaf_Interface_profile

    
    
    
    
    
    
    
    