---
- name: Cisco ACI vlan delete
  hosts: aci
  connection: local
  gather_facts: no
  vars:
    username: admin
    password: redhat123
    hostname: 10.69.151.244

  tasks:
    - name: delete switch leaf profile
      cisco.aci.aci_switch_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        state: absent
        validate_certs: false
      
    - name: Query a leaf profile
      cisco.aci.aci_switch_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        state: query
        validate_certs: false
      register: query_result_leaf_profile

    - name: print switch leaf profile output
      ansible.builtin.debug:
        var: query_result_leaf_profile