---
- name: Cisco ACI vlan create
  hosts: aci
  connection: local
  gather_facts: no
  vars:
    username: admin
    password: redhat123
    hostname: 10.69.151.244

  tasks:
    - name: create switch leaf profile
      cisco.aci.aci_switch_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        description: created by Ansible
        validate_certs: false
        state: present

    - name: Query a leaf profile
      cisco.aci.aci_switch_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        state: query
        validate_certs: false
      register: query_result_leaf_profile
    
    - name: print switch leaf profile output
      ansible.builtin.debug:
        var: query_result_leaf_profile

    - name: adding leaf selector to switch profile
      cisco.aci.aci_switch_leaf_selector:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        leaf: leaf_1
        leaf_node_blk: 101
        from: 101
        to: 101
        state: present
        validate_certs: false

    - name: Query leaf selector of switch profile
      cisco.aci.aci_switch_leaf_selector:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_profile: SW_Leaf_101_102
        leaf: leaf_1
        leaf_node_blk: 101
        state: query
        validate_certs: false
      register: query_result_leaf_selector

    - name: print output of query result for leaf selector
      ansible.builtin.debug:
        var: query_result_leaf_selector

    - name: Add a new leaf interface profile
      cisco.aci.aci_interface_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: SW_Leaf_101_102
        description: created by Ansible
        validate_certs: false
        state: present

    - name: Query leaf interface profile
      cisco.aci.aci_interface_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: SW_Leaf_101_102
        state: query
        validate_certs: false
      register: query_result_leaf_interface_profile
    
    - name: print output of query result for leaf interface profile
      ansible.builtin.debug:
        var: query_result_leaf_interface_profile
    
    - name: Create access port selector for leaf interface profile
      cisco.aci.aci_access_port_to_interface_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: SW_Leaf_101_102
        access_port_selector: SW_leaf_interface_profile_access_port
        port_blk: SW_leaf_interface_profile_access_port_blk
        from_port: 5
        to_port: 7
        state: present
        validate_certs: false

    - name: Query access port selector for leaf interface profile
      cisco.aci.aci_access_port_to_interface_policy_leaf_profile:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        leaf_interface_profile: SW_Leaf_101_102
        state: query
        validate_certs: false
      register: query_result_access_port_blk
    
    - name: print query result access port selector for leaf interface profile
      ansible.builtin.debug:
        var: query_result_access_port_blk

    - name: Disable CDP Interface policy
      cisco.aci.aci_interface_policy_cdp:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        name: Ansible_CDP_OFF
        admin_state: false
        state: present
        validate_certs: false
    
    - name: Query CDP Interface policy
      cisco.aci.aci_interface_policy_cdp:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        name: Ansible_CDP_OFF
        state: query
        validate_certs: false
      register: query_result_CDP_Interface_policy

    - name: print query result CDP Interface policy
      ansible.builtin.debug:
        var: query_result_CDP_Interface_policy

    - name: Enable LLDP Interface Policy
      cisco.aci.aci_interface_policy_lldp:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        lldp_policy: Ansible_LLDP_ON
        receive_state: true
        transmit_state: true
        state: present
        validate_certs: false

    - name: Query LLDP Interface policy
      cisco.aci.aci_interface_policy_lldp:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        lldp_policy: Ansible_LLDP_ON
        state: query
        validate_certs: false
      register: query_result_LLDP_Interface_policy

    - name: print query result LLDP Interface policy
      ansible.builtin.debug:
        var: query_result_LLDP_Interface_policy

    - name: Create Port Channel Policy
      cisco.aci.aci_interface_policy_port_channel:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        port_channel: Ansible_LACP_ACTIVE
        mode: active
        validate_certs: false

    - name: Query Port Channel Policy
      cisco.aci.aci_interface_policy_port_channel:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        port_channel: Ansible_LACP_ACTIVE
        state: query
        validate_certs: false
      register: query_result_Port_Channel_policy
    
    - name: print query result Port Channel Policy
      ansible.builtin.debug:
        var: query_result_Port_Channel_policy

    - name: Create leaf access port policy group
      cisco.aci.aci_interface_policy_leaf_policy_group:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        policy_group: Ansible_Leaf_PG_Policy
        lag_type: leaf
        cdp_policy: Ansible_CDP_OFF
        lldp_policy: Ansible_LLDP_ON
        validate_certs: false
    
    
    
    
    
    
    

    

    

    
    
    
    
    


    
    
    # - name: Query all cisco aci VLAN pool
    #   cisco.aci.aci_vlan_pool:
    #     host: "{{ hostname }}"
    #     username: "{{ username }}"
    #     password: "{{ password }}"
    #     validate_certs: false
    #     state: query
    #   register: vlan_pool
    
    # - name: print out VLAN
    #   ansible.builtin.debug:
    #     var: vlan_pool
    