---
- name: Cisco ACI
  hosts: aci
  connection: local
  gather_facts: no
  vars:
    username: admin
    password: redhat123
    hostname: 10.69.151.244

  tasks:
    - name: Query all cisco aci VLAN pool
      cisco.aci.aci_vlan_pool:
        host: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        state: query
      register: vlan_pool
    
    - name: print out VLAN
      ansible.builtin.debug:
        var: vlan_pool
    