---
- name: Cisco ACI
  hosts: aci
  connection: local
  gather_facts: no
  vars:
    username: admin
    password: redhat123
    hostname: 10.69.151.244

  tasks:
    - name: Query all cisco aci VLAN
      cisco.aci.aci_vlan:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ _password_ }}"
        validate_certs: false
        state: query
      register: vlan_output
    
    - name: print out VLAN
      ansible.builtin.debug:
        var: vlan_output
    