---
- name: Gather instance fact
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: print ec2 vars
      debug:
        var: " {{ ec2.instances }}"
    - name: Display inventory hostname variables
      debug:
        # var: inventory_hostname
        var: hostvars
      when: inventory_hostname == "{{ ec2.instances.private_dns_name }}"
    # - name: Gather EC2 instance facts
    #   amazon.aws.ec2_instance_facts:
    #     region: ap-southeast-2
    #     filters:
    #       instance-id: "{{ ec2.instance_id }}"
    #   register: ec2_facts
    # - name: Display EC2 instance facts
    #   debug:
    #     var: ec2_facts
