---
- name: AWS create instance
  hosts: localhost
  connection: local
  tasks:
    - name: Create an EC2 instance
      amazon.aws.ec2_instance:
        region: ap-southeast-2
        instance_type: t2.micro
        image_id: ami-0b145534e1950b975
        key_name: "linux_ssh"
        network_interfaces:
          - assign_public_ip: true
            # private_ip_address: 192.168.2.10
        security_group: default
        state: started
        wait: yes
      register: ec2

    - name: Display instance information
      debug:
        var: ec2
