---
- name: Gather instance fact
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    # - name: print ec2 vars
    #   debug:
    #     msg: "{{ ec2.instances[0].private_dns_name }}"
    - name: Display inventory hostname variables
      debug:
        var: inventory_hostname
      when: inventory_hostname == ec2.instances[0].private_dns_name
      
    - name: gather ip address from RHEL
      ansible.builtin.command: "hostname -I"
      register: ip_address
      when: inventory_hostname == ec2.instances[0].private_dns_name

    - name: Display ip address
      debug:
        var: ip_address.stdout
