---
- name: AWS create instance
  hosts: localhost
  connection: local
  tasks:
    - name: Display new ip details
      debug:
        msg: "New instance IP: {{ new_ip_address }}"

    - name: Create an EC2 instance
      amazon.aws.ec2_instance:
        region: ap-southeast-2
        name: "app{{ new_ip_id }}"
        instance_type: t2.micro
        image_id: ami-0b145534e1950b975
        key_name: "linux_ssh"
        #vpc_subnet_id: vpc-0113e355c682543a5
        network_interfaces:
          - assign_public_ip: true
            subnet_id: subnet-0dd132ff9f93f3e6f
            # private_ip_address: 192.168.1.4
            private_ip_address: "{{ new_ip_address }}"
        security_groups: 
          - "sg-04f26d8509c8019a8"
        vpc_subnet_id: my-vpc-01
        state: started
        wait: yes
      register: ec2

    - name: Display instance information
      debug:
        var: ec2

    - name: Display created instance information
      ansible.builtin.debug:
        msg: "Successfully created EC2 instance with name: {{ ec2.instances[0].tags.Name }}"
    
    - name: set stats for new ec2 instance
      ansible.builtin.set_stats:
        data:
          new_ec2_instance: "{{ ec2 }}"
