---
- name: Gather instance fact
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Display inventory hostname variables
      debug:
        var: inventory_hostname
    # - name: Gather EC2 instance facts
    #   amazon.aws.ec2_instance_facts:
    #     region: ap-southeast-2
    #     filters:
    #       instance-id: "{{ ec2.instance_id }}"
    #   register: ec2_facts
    # - name: Display EC2 instance facts
    #   debug:
    #     var: ec2_facts
